train_data_path: '../data/remove_strange_values/train_cluster.csv'
test_data_path: '../data/remove_strange_values/test_cluster.csv'
val_data_path: '../data/remove_strange_values/val_cluster.csv'
data_type: "SMILES"
target: "Permeability"
max_len: 250
augmentation: True
augmentation_ratio: 1
load_vocab: True
vocab_path: '../data/vocab.pkl'
use_HELM: True